[package]
edition = "2021"
name = "core"
version = "0.1.0"

[lib]
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
mio = { version = "0.8", features = ["os-poll", "net", "os-ext"] }
smoltcp = "0.8.2"
socket2 = "0.5"
