[package]
edition = "2021"
name = "core"
version = "0.1.0"

[lib]
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.133"
log = "0.4.17"
mio = {version = "0.8.4", features = ["os-poll", "net", "os-ext"]}
smoltcp = "0.8.1"
socket2 = "0.4.7"
