[package]
edition = "2021"
name = "main"
version = "0.1.0"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
core = { path = "../core" }
env_logger = "0.10"
libc = "0.2"
smoltcp = "0.10"
