[package]
edition = "2018"
name = "vpn"
version = "0.1.0"

[lib]
crate-type = ["dylib"]

[dependencies]
android_logger = "0.10.1"
jni = {version = "0.19.0", default-features = false}
lazy_static = "1.4.0"
libc = "0.2.112"
log = "0.4.14"
smoltcp = {path = "../smoltcp", version = "0.8.0"}
tokio = {version = "1.15.0", features = ["full"]}
