[package]
name = "vpn"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
smoltcp = { path = "../smoltcp", version = "0.8.0" }
jni = { version = "0.19.0", default-features = false }
