[package]
edition = "2021"
name = "vpn"
version = "0.1.0"

[lib]
crate-type = ["dylib"]

[dependencies]
android_logger = "0.13"
crossbeam = "0.8"
jni = { version = "0.21", default-features = false }
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
core = { path = "../../../../../../core" }
