name: Build Master Branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-host:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source/host

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install Rust targets
      run: rustup target add x86_64-unknown-linux-gnu

    - name: Build
      run: cargo build --target x86_64-unknown-linux-gnu

  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source/android

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Update Rust
      run: rustup update

    - name: Install Rust targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

    - name: Set up Android NDK
      run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "ndk;25.2.9519653"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
