name: Create Release

on: workflow_dispatch

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./source/android

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set Up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install Rust Targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

    - name: Set Up Android NDK
      run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "ndk;25.2.9519653"

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build With Gradle
      run: ./gradlew build
      
    - name: Publish Packages
      run: ./gradlew :android-local-vpn:publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
